### ISSUE TITLE
Padronizar Todas as Páginas da Home

### ISSUE THREAD

**Issue by enzoggqs** [fga-eps-mds/2022-1-PUMA-Doc#134]
### Descrição
Issue destinada a receber todas as páginas desenvolvidas da Home, na Release 4, e padroniza-las e unifica-las.

### Tarefas
- [x] Desenvolver Header;
- [x] Padronizar Página Sobre #114;
- [x] Padronizar Página Listagem das Disciplinas #115;
- [x] Padronizar Página Parceiros #117;
- [x] Padronizar Contato #118;

### Critérios de Aceitação
- [x] Todas as páginas estarem uniforma e devidamente padronizadas;
- [x] Todas as páginas serem inseridas no ambiente de homologação.
