### ISSUE TITLE
Criar ROADMAP ZenHub

### ISSUE THREAD

**Issue by Bruno-Felix** [fga-eps-mds/2022-1-PUMA-Doc#33]
### Descrição

Issue destinada ao desenvolvimento da visualização do ROADMAP das atividades, para a Release 1, no ZenhHub.

### Tarefas

- [ ] Definir o cronograma de atividades até a Release 1. 
- [x] Levantar todos os Épicos baseados nas atividades anteriores;
- [x] Atrelar todas as issues já trabalhadas com os épicos.

### Critérios de Aceitação

- [ ] O ROADMAP estar devidamente detalhado até a Release 1;
- Garantir que toda pessoa tenha acesso ao ZenHub.
